### ISSUE TITLE
Addons not working

### ISSUE THREAD

**Issue by BlueSparkGaming** [WheteThunger/MonumentAddons#50]
When i try /mainstall AirwolfOutpost i get the 404 error below. is there another way to install airwolf that im missing? 

[
![Screenshot 2024-05-20 214426](https://github.com/WheteThunger/MonumentAddons/assets/157326369/3e4863ad-3d06-4ca5-b5fe-9f2346fa1b96)
](url)

**Comment by WheteThunger** [comment]
It's OutpostAirwolf, not AirwolfOutpost.

**Comment by BlueSparkGaming** [comment]
Ah right ok. My mistake.

**Comment by Modarman** [comment]
I'm getting a simular error when I try to add recyclers to the rust. Like at the fishing village.  I  checked the spelling and to me it appears that the URL is incorrect.  I looked at the .cs and just can't figure out where it calls this to go and get the file to download.  Or I would change it so it would call out the correct URL.  I'm using this command :  mainstall safezonerecyclers and I get the same error.  Can you please help  with this.  Or better yet can you just help me get this  installed and working. thanks

**Comment by WheteThunger** [comment]
In your case, use:
```
mainstall SafeZoneRecyclers
```

It looks here:
https://github.com/WheteThunger/MonumentAddons/tree/master/Profiles

It's case-sensitive because it has to match what's on GitHub. I did push a change recently to GitHub (not to uMod yet) which knows the profile names and will convert them to the correct case for you to avoid this problem.

**Comment by Modarman** [comment]
Your right!  That worked and things look better now.  The next thing is do you have a common that installs extra shopping stores at the fishing villages?  I saw that on another map and if you can do that can you  please?  If you need a donation then I'll see to it.
Thanks
