### ISSUE TITLE
Monument Addons

### ISSUE THREAD

**Issue by andremelo90** [WheteThunger/MonumentAddons#51]
Hiho, hey ive come to test the latest version as of today and i think im doing something wrong, but masg add is not adding more than one item to the spawn group.

For instance, ive created and added an item:

```
masg create Loot_t3
masg add "dm tier3 lootbox"
```
When i try to add another item with
`masg add "dm tier2 lootbox"`

it returns the previous item being add
`Successfully added entity dm tier3 lootbox with weight 100 to spawn group Loot_t3`

**Comment by WheteThunger** [comment]
Thanks for reporting this issue. I just pushed a fix.
